### ISSUE TITLE
How to train the train_FKD.py and load config?

### ISSUE THREAD

**Issue by successhaha** [VILA-Lab/SRe2L#17]
Hi, this is a good work. But I ran into some issues while running the code. 

When I run the train code (as in train_FKD.py) as provided, it errors on the getitem method of ImageFolder_FKD_MIX not having the corresponding batch_config. 
The detailed description is as follows

======= FKD: dataset info ======

path: /home/xxx/SRe2L/relabel/FKD_cutmix_fp16/
num img: 50000
batch size: 1024
max epoch: 300

================================

300
load data successfully
=> loading student model 'resnet18'

Epoch: 0
Traceback (most recent call last):
  File "train_FKD.py", line 362, in <module>
    main()
  File "train_FKD.py", line 181, in main
    train(model, args, epoch)
  File "train_FKD.py", line 221, in train
    for batch_idx, batch_data in enumerate(args.train_loader):
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
Original Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xxx/anaconda3/envs/py37xxx/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xxx/SRe2L/validate/../relabel/utils_fkd.py", line 143, in __getitem__
    raise ValueError('config is not loaded')
ValueError: config is not loaded
How can I change it? Thanks.

**Comment by zeyuanyin** [comment]
Hi @successhaha 

Do you follow the instructions in https://github.com/VILA-Lab/SRe2L/blob/main/SRe2L/validate/README.md#preparation to modify PyTorch source code?

After the code replacement, batch_config will be loaded when running the code. 

https://github.com/VILA-Lab/SRe2L/blob/450939f05c80bd342ce756535e8c87a4d1e97357/SRe2L/validate/README.md?plain=1#L26

https://github.com/VILA-Lab/SRe2L/blob/450939f05c80bd342ce756535e8c87a4d1e97357/SRe2L/relabel/utils_fkd.py#L163-L177

**Comment by successhaha** [comment]
Thank you for your reply. I have solved this problem. I found a newer version of your code. I was using the old version before.
